name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to the app
        run: |
          curl -s -L -H "User-Agent: Mozilla/5.0" https://test-value-conversion-hmpjwbxab85ndns6t52efb.streamlit.app/
